# ワークフロー名
name: Genshinpy
on:
  push:
  schedule:
    # 定期実行する時間 毎週水曜日の26:00(UTC+9)
    - cron: '0 17 * * 3'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geckodriver-autoinstaller
          pip install beautifulsoup4==4.12.0
          pip install requests
          pip install lxml
          pip install Pillow
          pip install selenium
          pip install selenium-wire
          # pip install selenium==4.12.0
          pip install blinker
        
        # 必要なパッケージインストール

      - name: Run script
        run: |
          python Genshin.py
        # 定期実行するファイルを指定。
          
      # 以下、ファイルのコミットとプッシュ
      - name: Commit and Push
        run: |
          git config --global user.email "105225777+github-actions@users.noreply.github.com"
          git config --global user.name "AkaakuHub"
          git add .
          git commit -m "Auto commit by GitHub Actions"
          git push
