# ワークフロー名
name: Genshinpy
on:
  push:
  schedule:
    # 定期実行する時間
    - cron: '0 10 * * 0'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          # 必要なパッケージインストール

      - name: Run script
        run: |
          # 定期実行するファイルを指定。
          python python-sample.py
