name: Weekly Genshin Character Data Scraping

on:
  schedule:
    # Run every Sunday at 3:00 AM JST (18:00 UTC Saturday)
    - cron: '0 18 * * 6'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Chrome/Chromium for Puppeteer
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Puppeteer browsers
        run: npx puppeteer browsers install chrome

      - name: Run character data scraping
        run: node --import tsx/esm src/scrapers/weekly-scraper.ts
        env:
          NODE_ENV: production
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

      - name: Check for changes
        id: check-changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ api/
          git commit -m "Weekly data update - $(date '+%Y-%m-%d %H:%M:%S JST')"
          git push

      - name: Create summary
        if: always()
        run: |
          echo "## Weekly Scraping Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Date**: $(date '+%Y-%m-%d %H:%M:%S JST')" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "data/characters.json" ]; then
            CHARACTER_COUNT=$(jq '.characters | length' data/characters.json)
            echo "- **Characters Found**: $CHARACTER_COUNT" >> $GITHUB_STEP_SUMMARY
            echo "- **Last Updated**: $(jq -r '.lastUpdated' data/characters.json)" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
            echo "- **Changes**: ✅ New data committed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Changes**: ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scraping-logs
          path: |
            data/
            *.log
          retention-days: 7